# Generated by Django 4.1.6 on 2023-04-23 20:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_estoque_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='identificador_produto',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='venda',
            name='produto',
            field=models.ForeignKey(blank=True, limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='vendas', to='core.estoque'),
        ),
    ]
