# Generated by Django 4.1.6 on 2023-04-23 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_estoque_identificador_produto_alter_venda_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='identificador_produto',
        ),
        migrations.AddField(
            model_name='venda',
            name='produto_antigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_antigas', to='core.estoque'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estoque'),
        ),
    ]
