# Generated by Django 4.1.6 on 2023-04-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_estoque_identificador_produto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='produto_antigo',
        ),
    ]
